openapi: 3.0.0
info:
  title: IZE-Learning API
  version: 1.0.0
  description: This is API documentation using OpenAPI 3.0.
paths:
  /test/:
    get:
      summary: Get root
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: string
                example: Hola hola amigo testing api !

  /api/v1/registration:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                  example: name exmple
                email:
                  type: string
                  example: email@example.com
                password:
                  type: string
                  example: strongpassword123
                avatar:
                  type: string
                  example: https://example.com/avatar.jpg
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Please check your email, Activation code sent to email@example.com to activate your account
                  activationToken:
                    type: string
                    example: your-jwt-token-here
        '400':
          description: Bad request or Email already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Email already exists
