openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
  description: This is an example API documentation using OpenAPI 3.0.
paths:
  /:
    get:
      summary: Get root
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: string
                example: Welcome to the Example API!